server:
  tomcat:
    threads:
      max: 1024
      min-spare: 20
    max-connections: 8000
    connection-timeout: 20000
    max-http-form-post-size: -1
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: Admin

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl